name: feature_flags
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_core: ^2.1.1
  firebase_remote_config: ^3.0.4
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  package_info_plus: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
