name: feature_flags
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.1.0
  equatable: ^2.0.5
  firebase_core: ^2.8.0
  firebase_remote_config: ^3.0.15
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.0
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
